spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth?createDatabaseIfNotExist=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 4444

#spring:
#  h2:
#    console:
#      enabled: true
security:
  key: secret
